[platformio]
default_envs = esp32c6_4m

core_dir=/Users/petershipley/.platformio_zb

[env]

monitor_dtr = 0
monitor_rts = 1

check_tool = cppcheck
check_flags = 
    cppcheck: --enable=all --suppress=missingIncludeSystem

[env:esp32c6]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = esp32-c6-devkitc-1
framework = arduino
build_type = debug

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=4

; Required: enable the 802.15.4 driver in IDF config
; Without this esp_ieee802154_enable() will fail
board_build.sdkconfig = sdkconfig.defaults

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    ; ivanseidel/LinkedList @ ^1.3.3
    https://github.com/ivanseidel/LinkedList

[env:esp32c6_4m]
extends          = env:esp32c6
board            = esp32-c6-devkitm-1
board_upload.flash_size = 4MB

[env:esp32c6_8m]
extends          = env:esp32c6
board_upload.flash_size = 8MB


[env:esp32c5]
extends   = env:esp32c6
board     = esp32-c5-devkitc-1
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
build_flags =
     ${env.build_flags}
     -O2
     -Wall
     -g
     -fanalyzer
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=4
    -DTARGET_C5
    -DMO_LED

build_unflags = -Wliteral-suffix

; cxx_extra_flags = -Wno-literal-suffix
